#!/usr/bin/env sh
set -eu

if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  . ./.env
  set +a
fi

container run \
  --rm \
  --interactive \
  --tty \
  --entrypoint /bin/bash \
  "${IMAGE:-linux-desktop:latest}"
